---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: 移轉儲存資料時、會使用 REST API 手動建立儲存後端。移轉 VASA Provider 資料時，資料會從現有的 Derby 資料庫匯出，並匯入至 MongoDB 資料庫。 
---
= 遷移 VASA 提供者並更新 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== 遷移 VASA 提供者的步驟

. 若要在現有的 ONTAP 工具上啟用 VMware vSphere 的 Derby 連接埠 1527 ，請啟用 root 使用者，並透過 SSH 登入 CLI 。然後執行下列命令：
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. 部署適用於 VMware vSphere 10.3 的 OVA for ONTAP 工具。
. 新增您要移轉至 ONTAP 工具的 vCenter Server 執行個體，以取得 VMware vSphere 10.3 版本。如需詳細資訊、請參閱 link:../configure/add-vcenter.html["新增 vCenter Server 執行個體"] 。
. 透過 vCenter 伺服器 API 在本地為 ONTAP 工具插件加入儲存後端。
. 從 Swagger 或 Postman 發出下列 API 以進行移轉。
+
Curl -X POST https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs[]

+
您可以通過以下 URL 訪問 Swagger ：“ https://$FQDN_IP_PORT/, 例如： https://10.67.25.33:8443/[]。

+
[]
====
* HTTP 方法和端點 *

此 REST API 呼叫使用下列方法和端點。

|===


| * HTTP方法* | *路徑* 


| 貼文 | /API/v1 
|===
* 處理類型 *

非同步

* 目前範例 *

curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs'[] \ --header 'x-auth：<auth_token>' \ --header 'Content-Type：application/json' \ --data '{“otv_ip”：“xx.xx.xx.xx”，“vasa_provider_credentials”：{“用戶名”：“xxxxx”，“密碼”：“x*”，“用戶名”

其他版本移轉的要求本文：

{ “otv_ip”：“xx.xx.xx.xx”， “vasa_provider_credentials”：{ “用戶名”：“xxxxx”，“密碼”：“*******” } }

* JSON 輸出範例 *

工作物件即會傳回。您應該儲存工作識別碼、以便在下一步中使用。

{ "id" ： 123 、 "overview_id" ： "d50073ce-35b4-4c51-9d2e-4ce66f802c35" 、 "status" ： " 執行中 " }

====
. 使用 Swagger 中的下列 URI 檢查狀態：
+
[listing]
----
curl https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
+
完成工作後，請檢閱移轉報告。此報告包含在工作資料中，可從工作回應存取。

. 將適用於 VMware vSphere 儲存提供者的 ONTAP 工具新增至 vCenter Server 並link:../configure/registration-process.html["註冊 VASA Provider"]使用適用於 VMware vSphere 的 ONTAP 工具。
. link:../manage/enable-services.html["啟用 VASA Provider"]適用於 VMware vSphere 10.3 的 ONTAP 工具服務。
. 從維護主控台停止適用於 VMware vSphere 儲存供應商 9.10/9.11/9.12/9.13 VASA Provider 服務的 ONTAP 工具。
+
請勿刪除 VASA Provider 。

+
一旦停止舊的 VASA Provider ， vCenter Server 就會容錯移轉至適用於 VMware vSphere 的 ONTAP 工具。所有的資料存放區和 VM 都可以存取、並可從適用於 VMware vSphere 的 ONTAP 工具取得。

. 只有在觸發資料儲存發現作業後，從適用於 VMware vSphere 9.xxx 的 ONTAP 工具遷移的 NFS 和 VMFS 資料儲存才會顯示在適用於 VMware vSphere 10.3 的 ONTAP 工具中，這可能需要最多 30 分鐘才能完成。驗證資料儲存庫是否在 VMware vSphere 外掛程式使用者介面頁面的 ONTAP 工具概覽頁面上可見。
. 使用 Swagger 或 Postman 中的下列 API 執行修補程式移轉：
+
[]
====
* HTTP 方法和端點 *

此 REST API 呼叫使用下列方法和端點。

|===


| * HTTP方法* | *路徑* 


| 修補程式 | /API/v1 
|===
* 處理類型 *

非同步

* 目前範例 *

Curl -X 修補程式 https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43[]

* JSON 輸出範例 *

工作物件即會傳回。您應該儲存工作識別碼、以便在下一步中使用。

{ "id" ： 123 、 "overview_id" ： "d50073ce-35b4-4c51-9d2e-4ce66f802c35" 、 "status" ： " 執行中 " }

要求主體是空的，用於修補作業。


NOTE: UUID 是移轉後 API 所傳回的移轉 UUID 。

執行修補程式移轉 API 之後，所有 VM 都會遵守儲存原則。

====


.下一步
完成移轉並將 ONTAP 工具 10.3 登錄至 vCenter Server 之後，請遵循下列步驟：

* 等待 * 探索 * 完成，所有主機上的憑證都會自動重新整理。
* 請在開始資料存放區和虛擬機器作業之前，預留足夠的時間。所需的等待時間會因組態中的主機，資料存放區和虛擬機器數量而異。若未能等待，可能會導致間歇性作業故障。


升級後，如果虛擬機器的規範狀態已過期，請使用下列步驟重新套用儲存原則：

. 瀏覽至資料存放區，然後選取 * 摘要 * > * VM 儲存原則 * 。
+
在 * VM 儲存原則相容性 * 下的法規遵循狀態顯示為 * 過時 * 。

. 選取儲存 VM 原則和對應的 VM
. 選取 * 套用 *
+
在 * VM 儲存原則相容性 * 下的法規遵循狀態現在顯示為相容。



.相關資訊
* link:../concepts/rbac-learn-about.html["瞭解適用於 VMware vSphere 10 RBAC 的 ONTAP 工具"]
* link:../upgrade/upgrade-ontap-tools.html["從適用於 VMware vSphere 10.x 的 ONTAP 工具升級至 10.3"]




== 更新儲存複製適配器 (SRA) 的步驟

.開始之前
在復原計畫中，受保護站點是指虛擬機器目前運作的位置，而復原站點是指虛擬機器將被復原的位置。 SRM介面顯示復原計畫的狀態，其中包含受保護網站和復原網站的詳細資訊。在復原計畫中，「清理」和「重新保護」按鈕處於停用狀態，而「測試」和「執行」按鈕則保持啟用狀態。這表示該站點已準備好進行資料恢復。在遷移 SRA 之前，請先驗證一個網站處於受保護狀態，另一個網站處於復原狀態。


NOTE: 如果容錯移轉已完成，但重新保護仍在擱置中，請勿開始移轉。在繼續移轉之前，請先確認重新保護程序已完成。如果正在進行測試容錯移轉，請清理測試容錯移轉並開始移轉。

. 請依照下列步驟，在 VMware 網站恢復中刪除適用於 VMware vSphere 9.xx 的工具 ONTAP 介面卡：
+
.. 前往 VMware Live Site Recovery 組態管理頁面
.. 移至 * 儲存複寫介面卡 * 區段。
.. 從省略符號功能表中選取 * 重設組態 * 。
.. 從省略符號功能表中選取 * 刪除 * 。


. 在保護站點和恢復站點上執行這些步驟。
+
.. 按照中的步驟安裝適用於 VMware vSphere 10.3 介面卡的 ONTAP 工具link:../protect/configure-on-srm-appliance.html["在 VMware Live Site Recovery 應用裝置上設定 SRA"]。
.. 在 VMware Live Site Recovery 使用者介面頁面上，執行 * 探索陣列 * 和 * 探索裝置 * 作業，並確認裝置在移轉之前顯示為。



