---
permalink: concepts/ontap-tools-concepts-terms.html 
sidebar: sidebar 
keywords:  
summary: 下節說明文件中所使用的主要概念和詞彙。 
---
= 關鍵概念與詞彙
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下節說明文件中所使用的主要概念和詞彙。



=== ASA r2 系統

新的 NetApp ASA R2 系統提供統一化的硬體與軟體解決方案，可針對僅限 SAN 的客戶需求，提供簡化的體驗。 https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["瞭解 ASA R2 儲存系統"]。



=== 憑證授權單位（ CA ）

CA 是發行安全通訊端層（ SSL ）憑證的信任實體。



=== 一致性群組

一致性群組是以單一單元管理的磁碟區集合。在 ONTAP 中、一致性群組可為跨越多個磁碟區的應用程式工作負載提供簡易的管理和保護保證。深入瞭解 https://docs.netapp.com/us-en/ontap/consistency-groups/index.html["一致性群組"]。



=== 雙堆疊

雙堆疊網路是支援同時使用 IPv4 和 IPv6 位址的網路環境。



=== 高可用度（HA）

叢集節點是以 HA 配對方式設定、以進行不中斷營運。



=== 邏輯單元編號（LUN）

LUN 是用於識別儲存區域網路（ SAN ）內邏輯單元的編號。這些可定址的裝置通常是透過小型電腦系統介面（ SCSI ）傳輸協定或其封裝衍生工具之一存取的邏輯磁碟。



=== NVMe 命名空間和子系統

NVMe命名空間是一組可格式化為邏輯區塊的非揮發性記憶體。命名空間相當於FC和iSCSI傳輸協定的LUN、而NVMe子系統類似於igroup。NVMe子系統可與啟動器建立關聯、以便相關的啟動器存取子系統內的命名空間。



=== ONTAP 工具管理器

ONTAP 工具管理員可透過託管的 vCenter Server 執行個體和已建立的儲存後端、為 VMware vSphere 管理員提供更多的 ONTAP 工具控制權。ONTAP Tools Manager 可協助管理 vCenter Server 執行個體、儲存設備後端、憑證、密碼和記錄套件下載。



=== 開放式虛擬應用裝置（ OVA ）

ova 是一套開放式標準、用於封裝及散佈必須在虛擬機器上執行的虛擬應用裝置或軟體。



=== 恢復點目標（ RPO ）

RPO 是資料備份或複寫頻率的衡量標準。它代表停機後必須恢復資料的時間點，才能恢復業務營運。例如，如果組織有 4 小時的 RPO ，則在發生災難時，它可以容忍最多 4 小時的資料遺失。



=== SnapMirror 主動式同步（ SMAS ）

SnapMirror 主動式同步可讓業務服務持續運作、即使整個站台故障也沒問題、支援應用程式使用次要複本以透明方式容錯移轉。需要手動介入或自訂指令碼、才能使用 SnapMirror 主動同步觸發容錯移轉。詳細瞭解 https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["SnapMirror 主動同步"]。



=== 儲存設備後端

儲存設備後端是 ESXi 主機用來儲存虛擬機器檔案，資料和其他資源的基礎儲存基礎架構。儲存後端可讓 ESXi 主機存取及管理持續資料，為虛擬化環境提供必要的儲存功能與效能。



=== 儲存複寫介面卡（SRA）

SRA 是安裝在 VMware Live Site Recovery 應用裝置內的儲存廠商專屬軟體。此介面卡可在 Site Recovery Manager 與儲存虛擬機器（ SVM ）層級的儲存控制器之間、以及叢集層級組態之間進行通訊。



=== 儲存虛擬機器（ SVM ）

與在 Hypervisor 上執行的虛擬機器一樣、 SVM 是一個邏輯實體、可將實體資源抽象化。SVM 包含資料磁碟區和一或多個生命體、可透過這些生命體將資料提供給用戶端。



=== 統一且不一致的組態

* * 統一主機存取 * 表示兩個站台的主機都會連線到兩個站台上儲存叢集的所有路徑。跨站台路徑會跨越距離延伸。
* * 不統一的主機存取 * 表示每個站台中的主機僅連線到同一個站台中的叢集。不連接跨站台路徑和延伸路徑。
+

NOTE: 任何 SnapMirror 主動式同步部署都支援統一的主機存取；非統一的主機存取僅支援對稱式主動 / 主動式部署。





=== 虛擬機器檔案系統（ VMFS ）

VMFS 是專為在 VMware vSphere 環境中儲存虛擬機器檔案而設計的叢集式檔案系統。



=== 虛擬磁碟區（vVols）

VVols 為虛擬機器所使用的儲存設備提供磁碟區層級抽象化。它包含多項優點、可替代傳統 LUN 的使用方式。vVol 資料存放區通常與單一 LUN 相關聯、該 LUN 可作為 vVols 的容器。



=== VM 儲存原則

VM 儲存原則是在 vCenter Server 的原則和設定檔下建立。對於 vVols 、請使用 NetApp vVols 儲存類型提供者的規則來建立規則集。



=== VMware Live Site Recovery

VMware Live Site Recovery 可為 VMware 虛擬環境提供營運不中斷、災難恢復、站台移轉及不中斷營運的測試功能。



=== VMware vSphere API for Storage A感知 （ VASA ）

Vasa 是一組 API 、可將儲存陣列與 vCenter Server 整合以進行管理。此架構以多個元件為基礎、包括處理 VMware vSphere 與儲存系統之間通訊的 VASA Provider 。



=== VMware vSphere 儲存 API - 陣列整合（ VAAI ）

VAAI 是一組 API 、可在 VMware vSphere ESXi 主機和儲存裝置之間進行通訊。這些 API 包括一組主機用來將儲存作業卸載到陣列的原始作業。VAAI 可大幅改善儲存密集工作的效能。



=== vSphere Metro Storage 叢集

vSphere Metro Storage Cluster （ VMSC ）是一項技術、可在延伸叢集部署中啟用和支援 vSphere 。 NetApp MetroCluster 和 SnapMirror 主動式同步（前身為 SMBC ）支援 VMSC 解決方案。這些解決方案可在網域發生故障時、提供增強的營運持續性。恢復模式是根據您的特定組態選擇而定。深入瞭解 https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc["VMware vSphere Metro Storage 叢集"]。



=== vVols資料存放區

VVols 資料存放區是 VVols 容器的邏輯資料存放區呈現、由 VASA Provider 建立及維護。



=== 零RPO

RPO 是指恢復點目標、這是在指定時間內可接受的資料遺失量。零 RPO 表示無法接受資料遺失。
