---
permalink: automation/rest-implementation.html 
sidebar: sidebar 
keywords: ontap tools vmware vsphere rest api reference 
summary: REST 會建立一組通用的技術和最佳實務做法，但每個 API 的確切實作可能會因設計選擇而異。使用 ONTAP 工具之前，您應該先熟悉 VMware vSphere 10 REST API 的設計方式。 
---
= 適用於 VMware vSphere 10 REST API 的 ONTAP 工具實作詳細資料
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
REST 會建立一組通用的技術和最佳實務做法，但每個 API 的確切實作可能會因設計選擇而異。使用 ONTAP 工具之前，您應該先熟悉 VMware vSphere 10 REST API 的設計方式。

REST API 包括數種資源類別，例如 vCenter 和 Aggregate 。如需詳細資訊，請參閱link:../automation/api-reference.html["API 參考資料"]。



== 如何存取REST API

您可以透過 ONTAP 工具負載平衡器 IP 位址和連接埠來存取 VMware vSphere 10 REST API 的 ONTAP 工具。完整 URL 有幾個部分，包括：

* ONTAP 工具 IP 位址和連接埠
* API 版本
* 資源類別
* 特定資源


您需要在初始設定期間設定 IP 位址，而且連接埠永遠是 8443 。此外，對於 VMware vSphere 10 執行個體的特定 ONTAP 工具， URL 的第一部分是固定的。只有資源類別和特定資源會因端點而異。


CAUTION: 以下範例中的 IP 位址和連接埠值僅供說明之用。您必須針對環境變更這些值。

.存取驗證服務的範例
`\https://10.61.25.34:8443/virtualization/api/v1/auth/login`

此 URL 可用於使用 POST 方法要求存取權杖。

.列出 vCenter 伺服器的範例
`\https://10.61.25.34:8443/virtualization/api/v1/vcenters`

此 URL 可用於使用 GET 方法，要求已定義的 vCenter 伺服器執行個體清單。



== HTTP詳細資料

適用於 VMware vSphere 10 REST API 的 ONTAP 工具使用 HTTP 及相關參數來處理資源執行個體和集合。HTTP實作的詳細資料如下。



=== HTTP方法

REST API 支援的 HTTP 方法或動詞如下表所示。

[cols="15,15,70"]
|===
| 方法 | CRUD | 說明 


| 取得 | 讀取 | 擷取資源執行個體或集合的物件屬性。當與集合一起使用時，這會視為清單作業。 


| 貼文 | 建立 | 根據輸入參數建立新的資源執行個體。 


| 放入 | 更新 | 使用隨附的Json要求本文來更新整個資源執行個體。不會由使用者修改的金鑰值會保留下來。 


| 修補程式 | 更新 | 要求將要求中的一組選取變更套用至資源執行個體。 


| 刪除 | 刪除 | 刪除現有的資源執行個體。 
|===


=== 要求和回應標頭

下表摘要列出 REST API 使用的最重要 HTTP 標頭。

[cols="30,15,55"]
|===
| 標頭 | 類型 | 使用注意事項 


| 接受 | 申請 | 這是用戶端應用程式可以接受的內容類型。有效值包括 '\*/*' 或 `application/json`。 


| X-auth | 申請 | 包含存取權杖，可識別透過用戶端應用程式發出要求的使用者。 


| 內容類型 | 回應 | 由伺服器根據要求標頭傳回 `Accept`。 
|===


=== HTTP 狀態代碼

REST API 使用的 HTTP 狀態代碼如下所述。

[cols="15,20,65"]
|===
| 程式碼 | 意義 | 說明 


| 200 | 好的 | 表示未建立新資源執行個體的通話成功。 


| 201 | 已建立 | 已成功建立具有資源執行個體唯一識別碼的物件。 


| 202 | 已接受 | 已接受要求，並建立背景工作來執行要求。 


| 204 | 無內容 | 雖然未傳回任何內容、但要求仍成功。 


| 400 | 錯誤要求 | 無法辨識或不適當的要求輸入。 


| 401 | 未獲授權 | 使用者未經授權，必須進行驗證。 


| 403 | 禁止 | 由於授權錯誤、存取遭拒。 


| 404 | 找不到 | 要求中提及的資源不存在。 


| 409 | 衝突 | 建立物件的嘗試失敗、因為物件已經存在。 


| 500 | 內部錯誤 | 伺服器發生一般內部錯誤。 
|===


== 驗證

使用存取權杖執行用戶端對 REST API 的驗證。權杖和驗證程序的相關特性包括：

* 用戶端必須使用 ONTAP tools Manager 管理認證（使用者名稱和密碼）來要求權杖。
* Token 格式化為 JSON Web Token （ JWT ）。
* 每個權杖都會在 60 分鐘後過期。
* 用戶端的 API 要求必須在要求標頭中包含權杖 `x-auth`。


如需索取及使用存取權杖的範例，請參閱link:../automation/first-call.html["您的第一次 REST API 呼叫"]。



== 同步和非同步要求

大部分 REST API 呼叫都會快速完成，因此會同步執行。也就是說，他們會在申請完成後傳回狀態代碼（例如 200 ）。使用背景工作以非同步方式完成執行所需時間較長的要求。

發出非同步執行的 API 呼叫後，伺服器會傳回 202 HTTP 狀態代碼。這表示申請已被接受，但尚未完成。您可以查詢背景工作以判斷其狀態，包括成功或失敗。

非同步處理可用於多種類型的長時間執行作業，包括資料存放區和 vVol 作業。如需詳細資訊，請參閱 Swagger 頁面上 REST API 的工作管理員類別。
