---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: 將 vCenter Server 執行個體新增至 VMware vSphere 的 ONTAP 工具，以設定，管理及保護 vCenter Server 環境中的虛擬資料存放區。 
---
= 新增 vCenter Server 執行個體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將 vCenter Server 執行個體新增至 VMware vSphere 的 ONTAP 工具，以設定，管理及保護 vCenter Server 環境中的虛擬資料存放區。新增多個 vCenter Server 執行個體時，需要自訂 CA 憑證才能在 ONTAP 工具和每個 vCenter Server 之間進行安全通訊。

*關於此工作*

透過與 vCenter 整合， ONTAP 工具可讓您直接從 vSphere 用戶端執行資源配置，快照和資料保護等儲存工作，無需切換至獨立的儲存管理主控台。

.步驟
. 開啟網頁瀏覽器並瀏覽至 URL ： `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 選取 * vCenters * > * Add* 以內建 vCenter Server 執行個體。提供 vCenter IP 位址或主機名稱，使用者名稱，密碼和連接埠詳細資料。
+

NOTE: 您不需要管理員帳戶，即可將 vCenter 執行個體新增至 ONTAP 工具。您可以建立自訂角色，而無需具有有限權限的管理員帳戶。如 link:../concepts/rbac-vcenter-use.html["使用 vCenter Server RBAC 搭配適用於 VMware vSphere 10 的 ONTAP 工具"] 需詳細資訊、請參閱。



將 vCenter Server 執行個體新增至 ONTAP 工具會自動觸發下列動作：

* vCenter 用戶端外掛程式已登錄為遠端外掛程式。
* 外掛程式和 API 的自訂 Privileges 會套用至 vCenter Server 執行個體。
* 建立自訂角色以管理使用者。
* 外掛程式會在 vSphere 使用者介面上顯示為捷徑。

