---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: 當您第一次在 vSphere Client 中執行適用於 VMware vSphere 的 ONTAP 工具時、適用於 VMware vSphere 的 ONTAP 工具會探索 ESXi 主機、其 LUN 和 NFS 匯出、以及擁有這些 LUN 和匯出的 NetApp 儲存系統。 
---
= 探索儲存系統與主機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您第一次在 vSphere Client 中執行適用於 VMware vSphere 的 ONTAP 工具時、 ONTAP 工具會探索 ESXi 主機、其 LUN 和 NFS 匯出、以及擁有這些 LUN 和匯出的 NetApp 儲存系統。

.開始之前
* 所有 ESXi 主機均應開啟電源並進行連線。
* 所有要探索的儲存虛擬機器（ SVM ）都應該在執行中、而且每個叢集節點至少應針對使用中的儲存傳輸協定（ NFS 或 iSCSI ）設定一個資料 LIF 。


*關於此工作*

您可以隨時探索新的儲存系統或更新現有儲存系統的相關資訊、以取得最新的容量和組態資訊。您也可以修改 ONTAP 工具 for VMware vSphere 用於登入儲存系統的認證。

在探索儲存系統的同時、適用於 VMware vSphere 的 ONTAP 工具會從 vCenter Server 執行個體所管理的 ESXi 主機收集資訊。

.步驟
. 從 vSphere Client 首頁、選取 * 主機與叢集 * 。
. 右鍵單擊所需的數據中心，然後選擇 NetApp ONTAP tools*>* Update Host Data* 。
+
在 * 確認 * 對話方塊中，確認您的選擇。

. 選取狀態為的探索到的儲存控制器 `Authentication Failure`，然後選取 * 動作 * > * 修改 * 。
. 在「*修改儲存系統*」對話方塊中填寫必要資訊。
. 對 `Authentication Failure`狀態為的所有儲存控制器重複步驟 4 和 5 。


探索程序完成後、請執行下列動作：

* 使用適用於 VMware vSphere 的 ONTAP 工具，為在介面卡設定欄， MPIO 設定欄或 NFS 設定欄中顯示警示圖示的主機設定 ESXi 主機設定。
* 提供儲存系統認證資料。

